name: Sign Artifacts

on:
  push:
    branches: [ "main" ]

jobs:
  sign-job:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      -- name: Setup Trusted Signing
        uses: azure/trusted-signing-action@v0.4.0
        with:
          # Required account details
          trusted-signing-account-name: MUDClientSigningWestUS2
          endpoint: https://wus2.codesigning.azure.net/
          certificate-profile-name: NewPublicTrustProfile02
          
          # File configuration
          files-folder: ./bin 
          files-extension: exe,dll
